#!/usr/bin/env bash
#
# CUDA8/Fermi backend regression runner.
#
# Run inside the CUDA 8 container (Ubuntu 16.04 base, CUDA 8.0.61, C++11 tools),
# on a machine with the GTX 560 visible - every target below touches the GPU.
#
# Written against the container's old cmake: no -S/-B, no "--build -j".
#
#   ./ggml/src/ggml-cuda8/run-regression.sh            # G37 set (default)
#   ./ggml/src/ggml-cuda8/run-regression.sh --all      # every smoke target
#   ./ggml/src/ggml-cuda8/run-regression.sh <target>.. # explicit targets
#
# Env:
#   BUILD_DIR   build directory (default: <repo>/build-cuda8-parent)
#   NPROC       parallel build jobs (default: nproc)

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

BUILD_DIR="${BUILD_DIR:-${REPO_ROOT}/build-cuda8-parent}"
NPROC="${NPROC:-$(nproc 2>/dev/null || echo 4)}"

# The root CMakeLists sets CMAKE_RUNTIME_OUTPUT_DIRECTORY to <build>/bin, so
# executables do not land in the target's source-mirror directory. Resolve
# rather than assume - some targets also set RUNTIME_OUTPUT_DIRECTORY directly.
find_binary() {
    local t="$1" cand hit
    for cand in "${BUILD_DIR}/bin/$t" "${BUILD_DIR}/ggml/src/ggml-cuda8/$t"; do
        if [ -x "$cand" ]; then printf '%s' "$cand"; return 0; fi
    done
    hit="$(find "${BUILD_DIR}" -type f -name "$t" -perm -u+x 2>/dev/null | head -1)"
    if [ -n "$hit" ]; then printf '%s' "$hit"; return 0; fi
    return 1
}

# -- target sets --------------------------------------------------------------

# Targets exercising the most recent changes.
#   G37: the SOFT_MAX guard and the two corrected synthetic fixtures.
#   G38: grid clamps across the older kernels, plus the oversized-tensor smoke
#        that drives them past the 65535-block limit.
PRIMARY=(
    ggml-cuda8-oversized-smoke
    ggml-cuda8-ggml-backend-supports-op-smoke
    ggml-cuda8-ggml-backend-graph-compute-softmax-smoke
    ggml-cuda8-ggml-backend-graph-compute-attnlike-smoke
)

# Standalone kernel smokes for every kernel G38 rewrote. These use small
# shapes, so they check that the stride loops did not break the ordinary path.
KERNEL_REGRESSION=(
    ggml-cuda8-add-smoke
    ggml-cuda8-mul-smoke
    ggml-cuda8-scalar-smoke
    ggml-cuda8-reduce-smoke
    ggml-cuda8-reduce-max-smoke
    ggml-cuda8-softmax-smoke
    ggml-cuda8-rms-norm-smoke
    ggml-cuda8-rope-smoke
    ggml-cuda8-diagmask-smoke
    ggml-cuda8-getrows-smoke
)

# End-to-end graphs. Unaffected in principle by both G37 and G38.
GRAPH_REGRESSION=(
    ggml-cuda8-dispatch-all-smoke
    ggml-cuda8-ggml-backend-graph-builder-softmax-smoke
    ggml-cuda8-ggml-backend-graph-builder-attnlike-smoke
    ggml-cuda8-ggml-backend-graph-builder-q8_0-residual-scale-add-softmax-sumrows-smoke
    ggml-cuda8-ggml-backend-graph-builder-transformer-block-smoke
    ggml-cuda8-ggml-backend-graph-builder-attention-smoke
    ggml-cuda8-ggml-backend-graph-builder-e2e-smoke
)

if [ "$#" -gt 0 ] && [ "$1" = "--all" ]; then
    mapfile -t TARGETS < <(
        grep -o 'cuda_add_executable([a-zA-Z0-9_-]*' "${SCRIPT_DIR}/CMakeLists.txt" |
        sed 's/cuda_add_executable(//' | sort -u
    )
elif [ "$#" -gt 0 ]; then
    TARGETS=("$@")
else
    TARGETS=("${PRIMARY[@]}" "${KERNEL_REGRESSION[@]}" "${GRAPH_REGRESSION[@]}")
fi

# -- configure ----------------------------------------------------------------

# -- pick a usable cmake ------------------------------------------------------
#
# The container ships cmake 3.5.1, but the repo root requires 3.14+. The build
# tree was therefore generated by some other, newer cmake. 3.5.1 can still drive
# "cmake --build" (it just runs make), which is why building works and
# configuring does not.
#
# CMakeCache.txt records the cmake that generated it, so prefer that. Override
# with CMAKE_BIN=/path/to/cmake.

cmake_version_of() {
    "$1" --version 2>/dev/null | head -1 | awk '{print $3}'
}

cmake_at_least_314() {
    local v major minor
    v="$(cmake_version_of "$1")"
    [ -n "$v" ] || return 1
    major="${v%%.*}"
    minor="${v#*.}"; minor="${minor%%.*}"
    [ "$major" -gt 3 ] 2>/dev/null && return 0
    [ "$major" -eq 3 ] 2>/dev/null && [ "$minor" -ge 14 ] 2>/dev/null && return 0
    return 1
}

if [ -z "${CMAKE_BIN:-}" ] && [ -f "${BUILD_DIR}/CMakeCache.txt" ]; then
    CMAKE_BIN="$(sed -n 's/^CMAKE_COMMAND:INTERNAL=//p' "${BUILD_DIR}/CMakeCache.txt" | head -1)"
    [ -x "${CMAKE_BIN}" ] || CMAKE_BIN=""
fi

if [ -z "${CMAKE_BIN:-}" ]; then
    for cand in cmake3 /usr/local/bin/cmake /opt/cmake/bin/cmake "$(command -v cmake 2>/dev/null)"; do
        [ -n "$cand" ] || continue
        if command -v "$cand" > /dev/null 2>&1 && cmake_at_least_314 "$cand"; then
            CMAKE_BIN="$cand"; break
        fi
    done
fi

# Last resort: whatever is on PATH. Fine for --build, will fail on configure.
[ -n "${CMAKE_BIN:-}" ] || CMAKE_BIN="$(command -v cmake)"

echo "== cmake $(cmake_version_of "${CMAKE_BIN}")  (${CMAKE_BIN})"

if ! cmake_at_least_314 "${CMAKE_BIN}"; then
    echo "   warning: repo root needs cmake >= 3.14; configure steps will fail."
    echo "   set CMAKE_BIN=/path/to/newer/cmake if this run needs to reconfigure."
fi

# The CUDA 8 container ships an old cmake: no -S/-B (needs 3.13) and no
# --build -j (needs 3.12). Use the portable forms - they work on every version.
if [ ! -f "${BUILD_DIR}/CMakeCache.txt" ]; then
    echo "== configuring ${BUILD_DIR}"
    mkdir -p "${BUILD_DIR}" || exit 1
    ( cd "${BUILD_DIR}" && "${CMAKE_BIN}" "${REPO_ROOT}" -DGGML_CUDA8=ON -DGGML_CUDA=OFF ) || exit 1
else
    # Regenerate only when a CMakeLists.txt is newer than the cache. make re-runs
    # cmake as a prerequisite of targets it already knows about, but a target
    # added since the last configure fails with "No rule to make target" and
    # never gets that chance.
    stale=""
    for f in "${REPO_ROOT}/CMakeLists.txt" \
             "${REPO_ROOT}/ggml/CMakeLists.txt" \
             "${REPO_ROOT}/ggml/src/CMakeLists.txt" \
             "${SCRIPT_DIR}/CMakeLists.txt"; do
        [ -f "$f" ] || continue
        [ "$f" -nt "${BUILD_DIR}/CMakeCache.txt" ] && stale="$f"
    done

    if [ -n "$stale" ]; then
        echo "== regenerating (${stale##*/} is newer than the cache)"
        ( cd "${BUILD_DIR}" && "${CMAKE_BIN}" . > /tmp/cmake-regen.log 2>&1 ) || {
            echo "cmake regeneration FAILED (see /tmp/cmake-regen.log)"
            tail -20 /tmp/cmake-regen.log
            exit 1
        }
    fi
fi

# -- build --------------------------------------------------------------------

echo "== building ${#TARGETS[@]} target(s) with -j${NPROC}"
for t in "${TARGETS[@]}"; do
    # -j goes after "--" so it reaches make/ninja rather than cmake itself.
    "${CMAKE_BIN}" --build "${BUILD_DIR}" --target "$t" -- -j"${NPROC}" > /tmp/build-$t.log 2>&1
    if [ $? -ne 0 ]; then
        echo "BUILD FAILED: $t   (see /tmp/build-$t.log)"
        tail -30 /tmp/build-$t.log
        exit 1
    fi
done
echo "   build ok"

# -- run ----------------------------------------------------------------------

echo
pass=0
fail=0
failed_targets=()

for t in "${TARGETS[@]}"; do
    bin="$(find_binary "$t")"
    if [ -z "$bin" ]; then
        echo "MISSING  $t   (not found anywhere under ${BUILD_DIR})"
        fail=$((fail + 1)); failed_targets+=("$t")
        continue
    fi

    if "$bin" > "/tmp/run-$t.log" 2>&1; then
        printf 'PASS     %s\n' "$t"
        pass=$((pass + 1))
    else
        printf 'FAIL     %s   (see /tmp/run-%s.log)\n' "$t" "$t"
        fail=$((fail + 1)); failed_targets+=("$t")
    fi
done

# -- summary ------------------------------------------------------------------

echo
echo "== ${pass} passed, ${fail} failed"
if [ "${fail}" -ne 0 ]; then
    echo "failed:"
    for t in "${failed_targets[@]}"; do echo "  $t"; done
    exit 1
fi
